apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-riae
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0074-tenant/tkrw-pr714-0075-0074-app/devfile-sample-riae@sha256:2ec4f394b91a03f0d3ddf2f4e916f5f8dae02e899c82834bbbe0150a6df6dc76
        name: my-nodejs
        resources: {}
status: {}
